services:
  server-node:
    image: server-node:latest
    ports:
      - "8080:8080" # Map container port 8080 to host port 8080
    volumes:
      - ./log:/app/logs
    environment:
      - LOG_FILE=/app/logs/serverLogFile.log
      - PORT=8080
    networks:
      - app-network

  worker-node-1:
    image: worker-node:latest
    ports:
      - "8081:8081" # Map container port 8081 to host port 8081 for worker-node-1
    volumes:
      - ./log:/app/logs
    environment:
      - LOG_FILE=/app/logs/workerLogFile1.log
      - HOST=server-node
      - PORT=8080
    networks:
      - app-network

  worker-node-2:
    image: worker-node:latest
    ports:
      - "8082:8081" # Map container port 8081 to host port 8082 for worker-node-2
    volumes:
      - ./log:/app/logs
    environment:
      - LOG_FILE=/app/logs/workerLogFile2.log
      - HOST=server-node
      - PORT=8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
