FROM openjdk:21-jdk-slim

COPY build/libs/worker-node.jar /app/worker-node.jar
COPY docker/entrypoint.sh /app/entrypoint.sh

WORKDIR /app

EXPOSE 8081

ENV JAR_FILE=worker-node.jar

ENTRYPOINT ["./entrypoint.sh"]
